### ISSUE TITLE
[BUG] PVR service lookups on widgets

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/plugin.video.themoviedb.helper#1071]
### Describe the bug

I've noticed that this feature works perfectly with movies, as it will show both background artwork and clear logos, but for tv shows, it will only work when season and episode numbers are missing from EPG, while it won't if season and episode numbers are present (background artwork is missing).

### Steps To Reproduce

Browse items under PVR widgets in AH2 skin.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
It works for me. Need more details to understand the issue.

**Comment by r95sguy** [comment]
I remember facing the same issue before in AH2 PVR Guide, and the lookups didn't use to work for those tv shows with season and episode numbers, but it was fixed and it's now working for most tv shows in the guide, below are some examples:

TV show (lookups working)
![Screenshot 2](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113218125/e327acad-303d-4d51-b50d-991d6b685568)

TV show (lookups not working for artwork, but working for clear logo)
![Screenshot 3](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113218125/9e2e8d34-290a-4fc2-91ce-b76aa2a97476)

**Comment by jurialmunkey** [comment]
Sorry I still don't understand the issue. Looks like the service monitor is working correctly in those screenshots and providing additional metadata outside the list.

Are you saying the "problem" is that TMDbHelper is not modifying the listitems themselves and injecting new metadata? Because that's not how it works. The items provided by your PVR have nothing to do with TMDbHelper.

Kodi does not permit plugins to inject data into existing listitems. TMDbHelper cannot change the artwork inside the widget itself.

**Comment by r95sguy** [comment]
I understand that the plugin will not change the artwork inside the landscape thumbnail of the widget itself, I was referring to the background fanart, in the 1st screenshot the lookups worked perfectly (added clear logo + background fanart), but in the second screenshot, where the tv show has the season and episode numbers data from EPG, TMDBHelper plugin was able to get the clear logo but not the background fanart (no artwork in the background). 

It's not a big problem, just wanted to point this out, as this same issue used to happen under PVR Guide, and it since has been fixed.

**Comment by jurialmunkey** [comment]
Ah I understand now. 

This would be either a skin or PVR issue in that case.

All the artwork is retrieved together. If there's a clearlogo, then TMDbHelper is retrieving the artwork and item details. It isn't possible for TMDbHelper to get a clearlogo without first getting the item details -- it needs to get a TMDb ID to do the lookups to get the artwork and it gets the TMDb ID from the item details.

My guess is that your PVR client is putting something into either Art(fanart) or EPGEventIcon but the url is wrong and doesn't resolve to actual artwork hence the black screen. The other possibility is there's a variable in the skin that's wrong but I haven't been able to recreate this issue.

To know what is happening you would need to inspect the values for ListItem.Art(fanart) and ListItem.EPGEventIcon and then open the paths in a web browser to see if the images are correct.

**Comment by r95sguy** [comment]
I don't think it's coming from PVR client, as the same behavior continued even after I have disabled artwork download in PVR client settings.

As per the screenshots below, I don't have this problem inside Live TV Guide, I had faced this issue in reverse back in Nov, and it has been fixed in TMDBHelper plugin [https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/930](url) , maybe this could help!

TV Show in Guide (Background fanart showing)
![Screenshot 4](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113218125/d2407125-ed91-489f-a0ab-467811447a17)

TV Show in Widget (background fanart missing)
![Screenshot 5](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113218125/cde02f24-9939-4b98-8fce-b3041fa0b8df)

**Comment by jurialmunkey** [comment]
I still think this is a skin issue. If there's a clearlogo being retrieved, it would be unlikely for there not to be fanart too.

You can test this in AH2 by pasting the following code into `1080i/Home.xml` (assuming the issue is on the home screen) at the end of the file right before the `</controls></window>` tags (I've included those tags below so you can see where it goes - make sure they aren't duplicated in the file). Save file and (re)start Kodi.

You'll get a debug overlay at the top of the screen. When you focus the item in the widget, the cyan colour lines will show the contents of the ListItem label fanart and epgeventicon and clearlogo. The magenta lines will show what is in the TMDbHelper service (without EPGEventIcon since it doesnt set that).

```xml

        <control type="grouplist">
            <align>top</align>
            <orientation>vertical</orientation>
            <include content="Overlay_InfoLabel">
                <label> --IT LA $INFO[Container.ListItem.Label,","]</label>
                <textcolor>cyan</textcolor>
            </include>
            <include content="Overlay_InfoLabel">
                <label> --IT FA $INFO[Container.ListItem.Art(fanart),","]</label>
                <textcolor>cyan</textcolor>
            </include>
            <include content="Overlay_InfoLabel">
                <label> --IT CL $INFO[Container.ListItem.Art(clearlogo),","]</label>
                <textcolor>cyan</textcolor>
            </include>
            <include content="Overlay_InfoLabel">
                <label> --IT EI $INFO[Container.ListItem.EPGEventIcon,","]</label>
                <textcolor>cyan</textcolor>
            </include>

            <include content="Overlay_InfoLabel">
                <label> --SM LA $INFO[Container(99950).ListItem.Label,","]</label>
                <textcolor>magenta</textcolor>
            </include>
            <include content="Overlay_InfoLabel">
                <label> --SM FA $INFO[Container(99950).ListItem.Art(fanart),","]</label>
                <textcolor>magenta</textcolor>
            </include>
            <include content="Overlay_InfoLabel">
                <label> --SM CL $INFO[Container(99950).ListItem.Art(clearlogo),","]</label>
                <textcolor>magenta</textcolor>
            </include>
        </control>
    </controls>
</window>
```


Example output where you can see Service is filling details but my PVR is filling EPGEventIcon so I'm getting that as the background instead of fanart from the service monitor


![image](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4618719/c03e3bae-bd23-4b30-b11b-9d956e8c8257)

**Comment by r95sguy** [comment]
Yes, TMDBHelper retrieved fanart and clearlogo even when it didn't show up in the background, the only difference in those cases is season and episode numbers, it won't work when it's there, would that be related to a variable in the skin? Thanks for your help!

Fanart not showing up (season and episode numbers)
![Screenshot 6](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113218125/af6b465f-e0ac-4528-a735-70e6d83063d8)

Fanart showing (no season and episode numbers)
![Screenshot 7](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/113218125/ea950b09-33bf-4185-9727-a7035bf931d9)

**Comment by jurialmunkey** [comment]
EPGEventIcon will take precedence over any fanart fallback.

I can see in the IT EI line that your PVR is adding EPGEventIcon so that is the background being displayed in the skin.

You can test this by disabling EPGEventIcon
`Skin Settings > Appearance > EPGEventIcon for PVR fanart`

Pretty sure your PVR is adding a blank artwork.

Also note that fallback fanart is only displayed in AH2 if the container title matches the service title
You can override that behaviour by removing the check here
https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/6127b45163957c2ea9670fbd0e5c2cf7cdc89452/1080i/Includes_Images.xml#L98

Change that line to
```
<value condition="$EXP[Exp_HasBackgroundFanart] + !String.IsEmpty(Container(99950).ListItem.Art(fanart))">$INFO[Container(99950).ListItem.Art(fanart)]</value>
```

**Comment by r95sguy** [comment]
Yes, removing that check fixed the issue, now it's working perfectly! Thanks again, I'll close the issue.

**Comment by jurialmunkey** [comment]
> Yes, removing that check fixed the issue, now it's working perfectly! Thanks again, I'll close the issue.

Yeah I'll remove that from next skin release. It's a leftover from an issue that has since been fixed anyway.
