### ISSUE TITLE
[BUG] Dropped Trakt.tv shows still visible in "Next Episodes" section

### ISSUE THREAD

**Issue by Lortseam** [jurialmunkey/plugin.video.themoviedb.helper#1383]
### Describe the bug

When a TV show is marked as "dropped" on Trakt.tv, episodes from that show continue to appear in the "Next Episodes" section of the TMDB Helper plugin. Trakt.tv recently introduced the dropped status as a replacement for the legacy "hide" feature, which was previously used to exclude shows from the next episodes.

### Steps To Reproduce

1. Mark a TV show as "dropped" on your Trakt.tv account.
2. Navigate to the "Next Episodes" section in Kodi via the TMDB Helper plugin.
3. Observe the list of episodes.

Expected Result: Dropped shows and their episodes should be excluded from the "Next Episodes" section.

Actual Result: Episodes from the dropped show remain visible in the "Next Episodes" list.

### Checklist

- [x] I have searched the issues and this bug has not been reported.
- [x] I have updated TMDbHelper to the most recent version.
- [x] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
I think this should be addressed now in v6.7.0 onwards.

**Comment by bassemhelal18** [comment]
I still have this issue in the last update is there any setting I should do it was ok in 6.10 

Here my trkat app 
![image](https://github.com/user-attachments/assets/4bc59955-ac28-47ad-a027-adf19ea8e3c9)


And here what I got in tmdb

![image](https://github.com/user-attachments/assets/6594eecd-5f39-49bb-a061-e261990778c4)
