### ISSUE TITLE
[Feature] Option to prefer library artwork

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/plugin.video.themoviedb.helper#142]
As requested on AH github: https://github.com/jurialmunkey/skin.arctic.horizon/issues/83

Blurayx wrote:
---
Would it be possible to add fallback artwork option for The Movie DB  widgets Basically use the poster or fanart I have selected from my library/thetvdb because tvdb is more up to date, also my library poster will match my home screen widgets and solves the issue of missing artwork from  The Movie DB. I hope this makes sense

Home screen Widget
<a href="https://imgur.com/47J0gz6"><img src="https://i.imgur.com/47J0gz6.png" title="source: imgur.com" /></a>

Library
<a href="https://imgur.com/oZ06t8G"><img src="https://i.imgur.com/oZ06t8G.png" title="source: imgur.com" /></a>

Thanks

**Comment by Blurayx** [comment]
Will it be possible?
If it can, it would be amazing 😃

**Comment by jurialmunkey** [comment]
Yeah it should be possible. I think it makes sense to use library artwork first since you would expect consistency in how items are displayed.

**Comment by jurialmunkey** [comment]
@Blurayx - I think this should be working now. If the item is recognised as being in the library then the plugin should use the library artwork. Can you test latest github version and confirm?

**Comment by Blurayx** [comment]
unfortunately still not working. please test Empire.
https://www.thetvdb.com/series/empire-2015
https://www.themoviedb.org/tv/61733-empire?language=en-US

**Comment by Blurayx** [comment]
should it work by default?

**Comment by jurialmunkey** [comment]
Do you have this option enabled in TMDbHelper settings?
![Honeyview_screenshot708](https://user-images.githubusercontent.com/4618719/78099434-99bef380-742d-11ea-9112-e3e1fb7ab8db.jpg)


As long as you have that option enabled and the show is actually matching with the library, then you should get library posters.

**Comment by jurialmunkey** [comment]
Ah I just realised you're pointing to a tvshow poster but what is being shown is the season poster. That's why it is different.

**Comment by jurialmunkey** [comment]
For season posters, the poster is attached to each episode individually, so there isn't an item to grab it from.

It works properly for tvshow posters:
Original:
![Honeyview_screenshot709](https://user-images.githubusercontent.com/4618719/78100225-e9062380-742f-11ea-9abf-78c342be71d8.jpg)

Then I changed the artwork in the library and it is showing in TMDbHelper:
![Honeyview_screenshot711](https://user-images.githubusercontent.com/4618719/78100236-f3282200-742f-11ea-8e2f-f207d0d87c1a.jpg)

**Comment by jurialmunkey** [comment]
I'm going to have to think about how I might address the season posters without causing issues in other places.

**Comment by Blurayx** [comment]
t

> For season posters, the poster is attached to each episode individually, so there isn't an item to grab it from.
> 
> It works properly for tvshow posters:
> Original:
> ![Honeyview_screenshot709](https://user-images.githubusercontent.com/4618719/78100263-00dda780-7430-11ea-8739-bd1db04f6f11.jpg)
> 
> Then I changed the artwork in the library and it is showing in TMDbHelper:
> ![Honeyview_screenshot711](https://user-images.githubusercontent.com/4618719/78100236-f3282200-742f-11ea-8e2f-f207d0d87c1a.jpg)

Yes. I have library posters enabled. sorry to be so fussy I don't always like season posters lol
If it's going to be complicated please do not compromise your all the hard work you've done so far

**Comment by jurialmunkey** [comment]
@Blurayx - I think this should now be fixed. You will need latest version of TMDbHelper and latest version of Arctic Horizon. Next Aired posters should now match library posters. Can you test and confirm?

**Comment by Blurayx** [comment]
Perfect!!
Thanks
