### ISSUE TITLE
Impossible to select default player

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#1675]
### Describe the bug

Hi @jurialmunkey :)

Since recent updates, I can no longer select a custom JSON player as the Default Player in TMDb Helper unless that player is one of the built-in players shipped inside the addon’s own resources/players folder.
Only the built-in players are listed. The only custom file I’m able to select is a very simple “Notification.json” I created (attached). My usual custom player Pastebin.json — which used to be selectable — is now invisible in the “Default player” picker.

As a temporary workaround, I manually edited `settings.xml` to force my desired default players. 

### Steps To Reproduce

- Place a custom player file (`Pastebin.json`, attached) in the user players folder (`addon_data/plugin.video.themoviedb.helper/players/`).

- Open TMDb Helper → Settings → Players → Default player.

**Observe:** only built-in players are shown; the external/custom player does not appear.

(Control) A minimal “`Notification.json`” (attached) does appear and can be selected.

### Expected behavior

Any valid custom player placed in the user players directory should appear in the “Default player” list and be selectable as before.

### Debug log

Action to open the Default Player picker is logged (`route_taken set_defaultplayer`) and the “Build players / Build player dialog / Done!” messages occur, followed by DialogSelect opening. (debug log attached)

Environment and versions are listed below.

### Environment

- Kodi: 21.2 (21.2.0) – Android ARM 64-bit, running on NVIDIA SHIELD Android TV (Android 11)
- TMDb Helper: 6.10.6 (repository.jurialmunkey 3.5)
- script.module.jurialmunkey: 0.2.29
- Skin: Arctic Fuse 2.10.10

### Player files attached

- `Notification.json` (non-resolvable; only closes the selection dialog) — this one does show up.
- `Pastebin.json` (resolvable TMDb→vStream with play_movie/play_episode) — this one is invisible in the picker.

### Additional context 

While reviewing the debug log, I noticed that I made an idiot mistake: `Pastebin.json`’s `fallback` references `Animesjson play_episode` (missing `.json`, likely `Animes.json play_episode`). If stricter validation is applied, could this be why the player is excluded from the **Default player** list? 

The attached file reproduces the issue.

[Notification.json](https://github.com/user-attachments/files/22976991/Notification.json)
[pastebin.json](https://github.com/user-attachments/files/22976990/pastebin.json)
[kodi.log](https://github.com/user-attachments/files/22976994/kodi.log)

### Screenshots and Additional Info

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/74bfcdc3-ef59-4849-88cb-63517613230b" />

### Checklist

- [x] I have searched the issues and this bug has not been reported.
- [x] I have updated TMDbHelper to the most recent version.
- [x] I have described the bug and included steps to reproduce the issue
- [x] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Thanks! Really appreciate you taking the time to give me a proper debug log, example player, and explanation. It was reported in this other thread here https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/1671 but no one was giving me a log or example player which was making things difficult!

I think I see the issue. It's related to the "assert" values being checked when they shouldn't be - since setting a default player doesn't have an associated item, it always fails the assert check. Fix incoming.

**Comment by jurialmunkey** [comment]
This commit should fix the issue https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/fe8046ba3824b57695bcb788814649d5eba45f3e

**Comment by sousouille** [comment]
@alKODIque & @jurialmunkey thanks to you.
The issue is not fixed for me.

**Comment by alKODIque** [comment]
Hi @jurialmunkey 
Thanks for the super quick turnaround on [#1675](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/fe8046ba3824b57695bcb788814649d5eba45f3e)

I can confirm the fix 🥳
After updating to the build referenced in your comment, the Default player picker lists my custom JSON players again and the previous reproduction now succeeds.

**Log excerpt shows the player list being rebuilt and the dialog opening without errors:**

```
lib.script.router - route_taken set_defaultplayer
TMDbHelper - 00 Build players...
TMDbHelper - 100 Build player dialog...
TMDbHelper - Done!
```

Much appreciated,
thanks for the fix and for maintaining this awesome addon! 🙏

**Comment by alKODIque** [comment]
@sousouille

**Just a heads-up:** please make sure you’re actually on the build that includes the fix for **[#1675](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/fe8046ba3824b57695bcb788814649d5eba45f3e)** (the one referenced in jurial’s comment) - **now avalable on v6.10.7**.

In Kodi: **Add-ons → My add-ons → TMDb Helper → Update → Check for updates**
(or reinstall from **jurialmunkey’s repository**), then confirm the add-on **version/build** shown there.

After updating, the **Default player** picker should list your custom JSON players again. If it still doesn’t:

- In TMDb Helper **Settings → Players**, use **Update players** (re-download your players from URL), then **restart Kodi**.

I’ve re-tested on my side and it’s working again. 👍

https://github.com/user-attachments/assets/11439d9d-e77f-458b-8e02-e8bd5bfcb0fb

**Comment by sousouille** [comment]
Hi @alKODIque , believe me. Before I post my negative reply, I have done this test on Windows and Kodi v22a:
- update auto in 6.10.7 
- update players, then ok.
- go back to setup tmdbh, and see the same bug

- second test, I uninstalled tmdbh by switch on estuary and disable arctic fuse 2. I remove my conf to go on new fresh install 
- then reinstall tmdbh and make same test and same result

This morning, I test on Android on my phone on Kodi v21.2, and it's ok. 

I'll check again on windows platform with Kodi 22 and let you know if I was tired last morning 😅

Thanks for your work both

**Comment by sousouille** [comment]
I confirm it's OK. have a good we
