### ISSUE TITLE
Add_path not working

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#27]
In the later versions of TMDBhelper it looks like the default play action is causing problems with add_path feature. 
When running the following for VideoInfo widgets onclick:
RunScript(plugin.video.themoviedb.helper,add_path=$INFO[ListItem.FolderPath],call_id=1137,delay=0.35,prevent_del)
TMDbHelper.Path.Current gets set with the info=play instead of info=details, resulting in looped busydialog and no Action(info) being triggered 
Window(Home).Property(TMDbHelper.Path.Current): plugin://plugin.video.themoviedb.helper/?info=play&type=movie&tmdb_id=449562

**Comment by jurialmunkey** [comment]
Yep you're right. 

I've just pushed a commit that should hopefully fix this issue. Can you test and confirm?

**Comment by skyfsza** [comment]
Thanks for update, Movies are now working, TMDbHelper.Path.Current path example:
plugin://plugin.video.themoviedb.helper/?info=details&fanarttv=False&type=movie&tmdb_id=604

For TV Shows, still have a dialogbusy loop, TMDbHelper.Path.Current path:
plugin://plugin.video.themoviedb.helper/?info=seasons&fanarttv=False&type=tv&tmdb_id=1405

Side request, could you remove the fanarttv=False when using add_path?

**Comment by jurialmunkey** [comment]
> 
> 
> For TV Shows, still have a dialogbusy loop, TMDbHelper.Path.Current path:
> plugin://plugin.video.themoviedb.helper/?info=seasons&fanarttv=False&type=tv&tmdb_id=1405

Okay, should be fixed now.



>
> 
> Side request, could you remove the fanarttv=False when using add_path?

Why are you adding `fanarttv=False` to the path? The skin *only* checks for `fanarttv=True` - adding False does nothing at all. 

If you want to add `fanarttv=True` to the add_path you can do:  
`add_path=$INFO[ListItem.FolderPath,,&amp;fanarttv=True]`

**Comment by skyfsza** [comment]
Thanks, TV shows now working.

i'm not setting fanarttv=False, figured the addon was doing it?
onclick i'm using
RunScript(plugin.video.themoviedb.helper,add_path=$INFO[ListItem.FolderPath],call_id=1137,delay=0.35,prevent_del)

Using add_path=$INFO[ListItem.FolderPath,,&amp;fanarttv=True] did the trick, thanks!

**Comment by skyfsza** [comment]
Another quick Q on the add_path. 

I seem to be having an issue with path history. If i use add_path, TMDB_Info.xml (taken from AZ2)  correctly launches DialogVideoInfo, however when I onback from VideoInfo, it does not appear to remove the item from the path history which then causes DialogVideoInfo to be launched again with the same title. onback from the 2nd VideoInfo correctly removes the path and returns to home.

This issue only seems to happen when I have 1 path, If I do further add_paths everything works as expected.

Video showing the problem:
https://imgur.com/a/MCzf9Vz

**Comment by jurialmunkey** [comment]
Do you have this line in DialogVideoInfo?
https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/master/1080i/DialogVideoInfo.xml#L10

**Comment by skyfsza** [comment]
Yes, I have the del_path in DialogVideoInfo.

Just installed AZ2 and I am seeing similar problems with add_path as I do in AuraMod, although now it seems to be a looping issue rather than just double VideoInfo.

When clicking on a movie inside VideoInfo that is from one of the tmdb lists, add_path correctly launches VideoInfo, however when closing / onback, you get stuck in a loop of VideoInfo's being triggered.  If you change default action from "show information" to "play" you get a loop of the play dialog opening. 

Video with default action play:
https://imgur.com/a/2xls6S0

Video with default action show info
https://imgur.com/a/rCMGZUZ

**Comment by jurialmunkey** [comment]
Okay, yep can confirm. Not quite sure what is causing it yet. I'll keep you posted.

**Comment by jurialmunkey** [comment]
@skyfsza - Can you test latest when you get the chance? It seems like I've fixed the issue but I'm still not entirely clear on what the underlying cause is. 

For some reason the listitem.folderpath was getting executed but I have no idea why - I've just hacked things to avoid the issue entirely by forcing info=details if added with add_path so it isn't possible to execute the play/info path.

**Comment by skyfsza** [comment]
Show Info / Play loop looks like it's fixed, tested on AuraMod and AZ2.

I still seem to have the issue with onback reopening video info, this however is only happening on AuraMod and not AZ2.   

Any ideas on what I could be missing?  

Problem only happens when I have 1 path added. If I add more paths, then it onbacks correctly.

Video with multiple paths:
https://imgur.com/a/3olwLyq

With only 1 Path:
https://imgur.com/a/tXIwetA

my onclick for tmdb widgets inside VideoInfo:
RunScript(plugin.video.themoviedb.helper,add_path=$INFO[ListItem.FolderPath,,&amp;fanarttv=True],call_id=1137,delay=0.35,prevent_del)

DialogVideoInfo onunload (my tmdb_info window ID is 1134):
<onunload condition="Window.IsVisible(1134)">RunScript(plugin.video.themoviedb.helper,del_path,call_id=1137)</onunload>

If I monitor Window(Home).Property(TMDbHelper.Path.Current) in devhelper, I can see that the path is only being cleared after onback on the 2nd VideoInfo that opens.

**Comment by jurialmunkey** [comment]
>
> 
> If I monitor Window(Home).Property(TMDbHelper.Path.Current) in devhelper, I can see that the path is only being cleared after onback on the 2nd VideoInfo that opens.

There's your answer. The "prevent_del" param is stopping the property from being cleared on the last time.

When `prevent_del` is set, `del_path` is prevented from deleting the path and instead it deletes the `prevent_del` path.

Basic flow is:
1. Onclick `add_path` action adds the path to the history with `prevent_del` set.
2. Dialog Video Info is closed which triggers `<onunload>` and thus the `del_path` action
3. Because `prevent_del` is set, `del_path` doesn't delete the path and instead deletes the `prevent_del` lock.
4. User clicks another item and process repeats: goto 1.
5. OR... User presses back which closes info dialog and triggers `<onunload>`
6. HOWEVER, because prevent_del was already removed, instead the path is replaced with the previous path (and so the user can go "back" to previous item).

What is likely happening is your `<onunload condition="Window.IsVisible(1134)">` is not triggering the first time around because 1134 is not yet open.

AFAICT, onunload triggers after WindowClose animations complete. What happens in AZ2 is that the animations mean that 1134 is active before they complete and the condition triggers anyway, whereas in your skin the window is probably not active. 

You can probably remove the condition altogether and have things work fine. I can't even remember what issue that condition was addressing. It should work fine if you do:
`<onunload>RunScript(plugin.video.themoviedb.helper,del_path,call_id=1137)</onunload>`

**Comment by skyfsza** [comment]
That did the trick.... feel like a bit of an idiot for not having tried that :) 

Thanks for all your help, much appreciated.

**Comment by skyfsza** [comment]
FYI, if you remove the Window.IsVisible condition, when you open DialogVideoInfo on non tmdbhelper items, the del_path is triggered which leaves you stuck on a dialogbusy from TMDB_Info.xml.

Went with this in DialogVideoInfo, which seems to work:
`    <onunload condition="!String.IsEmpty(Window(Home).Property(TMDbHelper.Path.Current))">RunScript(plugin.video.themoviedb.helper,del_path,call_id=1137)</onunload>
`

**Comment by jurialmunkey** [comment]
> 
> 
> FYI, if you remove the Window.IsVisible condition, when you close DialogVideoInfo on non tmdbhelper items, the del_path is triggered which leaves you stuck on a dialogbusy from TMDB_Info.xml.
> 
> Went with this in DialogVideoInfo, which seems to work:
> ` <onunload condition="!String.IsEmpty(Window(Home).Property(TMDbHelper.Path.Current))">RunScript(plugin.video.themoviedb.helper,del_path,call_id=1137)</onunload>`

Ah! I knew there was a reason I added that condition originally!

Your solution works well!
