### ISSUE TITLE
Netflix player not working

### ISSUE THREAD

**Issue by Desperados85** [jurialmunkey/plugin.video.themoviedb.helper#294]
The "play with Netflix" player doesn't work. 
I found a closed issue [#251](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/251#issuecomment-642690594) and looked for the commit you made in "resources/lib/kodi/infolabels.py"
The changes are still there but it doesn't work anymore (at least for me). I'm on Netflix version 1.8.0.

When I try to play The Old Guard I get a dialog "type of search" with 4 options; by term, by audio language, by subtitle language and by genre/subgenre ID. When I choose the first option I see the search keyboard in a flash searching for "The Old Guard" but within a second I get the error "item not found".
When I use the "search with Netflix" player however it does find the movie..

Can someone check if they're having the same issue?

**Comment by jurialmunkey** [comment]
Works fine for me. I was able to play this exact movie using the default "Play with Netflix" player and using the normal 1.8.0 version of Netflix without any modification.

**Comment by Desperados85** [comment]
That's weird, I don't know what could be wrong on my end.. 
I checked the Netflix addon, played Project Power and The Old Guard, just to check if they would actually play, and both played fine. 
I then restarted Kodi, opened TMBD Helper and tried to play both movies using the Netflix player.
The weird thing is I didn't get the dialog with the four choices this time but still got the same error "item not found". 

I uploaded a log, could you maybe check if you see something strange? 

https://paste.kodi.tv/xujazicihu

**Comment by jurialmunkey** [comment]
The line below indicates that Netflix search is probably timing out and not returning any results. I've had some issues with timeouts in the Netflix plugin recently (both via players and in the actual Netflix plugin itself).
```
ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/search/search/The Old Guard/
```

**Comment by jurialmunkey** [comment]
```
ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/search/search/The Old Guard/
```

There's the issue. Netflix plugin is not return any results. Probably timed out - I've noticed more than usual timeout issues with the Netflix plugin recently (both via player and the plugin itself).

**Comment by Desperados85** [comment]
OK thanks for looking at my log, appreciate it!
I'll just keep using the Netflix addon widgets for playback, and from time to time check the player to see if it's working.

**Comment by jurialmunkey** [comment]
I started having issues in 1.9.0 which were resolved via this patch I've made for Netflix plugin: https://github.com/CastagnaIT/plugin.video.netflix/pull/856

Might be worth seeing if that solves your issues too.

**Comment by Desperados85** [comment]
Thank you!! I will try it out this weekend 😁

**Comment by Desperados85** [comment]
> I started having issues in 1.9.0 which were resolved via this patch I've made for Netflix plugin: [CastagnaIT/plugin.video.netflix#856](https://github.com/CastagnaIT/plugin.video.netflix/pull/856)
> 
> Might be worth seeing if that solves your issues too.

So I've been busy a couple of days and decided to give your patch a try just now.
Saw your patch was just merged with the new Netflix update so that made it easy for me lol.
Too bad it still doesn't work for me, probably still timing out. I know that's an issue on my side so I'll just close this issue.
Thanks for helping anyways!
