### ISSUE TITLE
Error when first time starting tmdb helper after clean install

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#643]
When I first time start tmdb helper (to be more precise, when first time entering in some list) after clean install or delete all cache, I get this error. It only happens once and never again (until the next clean install or clear the cache) and as far as I noticed only on android devices. It's enter in list with a lack of some artworks and informations, I exit from list and come back again and everything works. It's not big deal, just to let you know.
https://paste.kodi.tv/itidadihed.kodi

**Comment by jurialmunkey** [comment]
Is this using main matrix branch? What version?

**Comment by matke-84** [comment]
@jurialmunkey
With any version. I've seen this for a long time, but I've never paid so much attention. But considering testing different versions in the last few days, I remembered this one as well.

**Comment by jurialmunkey** [comment]
Can you test using the normal matrix branch with the version I just pushed and see if that helps?

FYI - I'm going to abandon the delayed cache write branch for the moment. The performance cost in copying memory addresses to make it work properly means that any gains aren't worthwhile. There's no point adding additional complexity to the code for only minimal benefit - I'll look for gains elsewhere.

**Comment by matke-84** [comment]
> Can you test using the normal matrix branch with the version I just pushed and see if that helps?

No, it still throws out the error on first entry.

> FYI - I'm going to abandon the delayed cache write branch for the moment. The performance cost in copying memory addresses to make it work properly means that any gains aren't worthwhile. There's no point adding additional complexity to the code for only minimal benefit - I'll look for gains elsewhere.

Ok, I hope you find a better solution, we really need speed now. Without this, we lost at least two seconds, it seems small, but on Android it means a lot. 🙂
Just you know, the problem with TMDb artwork quality started with the new item builder version 4.5.32. Not related with delayed cache.

**Comment by jurialmunkey** [comment]
Can you try that version ^^^

**Comment by matke-84** [comment]
@jurialmunkey
Unfortunately it still throws out error.

**Comment by matke-84** [comment]
@jurialmunkey
Do you need maybe new log file for this?

**Comment by jurialmunkey** [comment]
> @jurialmunkey Do you need maybe new log file for this?

Yeah maybe a full log with kodi debug logging enabled. It's unusual as I never clear `_win` or `_monitor` attributes and they're created on the Class `__init__` so they should always exist whilst the class exists.

**Comment by matke-84** [comment]
> > @jurialmunkey Do you need maybe new log file for this?
> 
> Yeah maybe a full log with kodi debug logging enabled. It's unusual as I never clear `_win` or `_monitor` attributes and they're created on the Class `__init__` so they should always exist whilst the class exists.

See if this is ok. 
https://paste.kodi.tv/ihayipegem.kodi

**Comment by jurialmunkey** [comment]
Thanks, log was useful.

Can you test latest and see if that helps. Even if it works, please get me a log as I'd like to see how many connection attempts it needs.

**Comment by matke-84** [comment]
@jurialmunkey
Still throws out error. It’s too big for a clipboard so I upload log file.
https://files.fm/f/k5qwvsn56

**Comment by jurialmunkey** [comment]
A bit closer! Hopefully this will solve it.

**Comment by matke-84** [comment]
> A bit closer! Hopefully this will solve it.

Bingo! 🙂
