### ISSUE TITLE
Local videos not playing from next up widget

### ISSUE THREAD

**Issue by roc16** [jurialmunkey/plugin.video.themoviedb.helper#857]
### Describe the bug

Hi @jurialmunkey it seems the issues I reported previously have reoccurred with the laters version (#767 & #339). 
I’m version 4.11.18. 

### Steps To Reproduce

Try to play anything from the next up widget

### Debug log

I’m hoping this is reproducible your end (or the previous logs help). If not I will get you a log. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Ah sorry! I know exactly why this happened. 

I started threading the extra id lookups to help speed up the player selection dialog. I only join the thread back if a specific player in the dialog needs those ids, otherwise I don't wait for it. I just forgot sometimes tvdb id is needed for tv library matches. 

My TV library uses tmdb ids, not tvdb, so I never notice when I make these breaking changes - I need to put a big comment in the code to remind myself to check this tvdb based library test case first! 

Will fix later today.

**Comment by roc16** [comment]
No problem and no rush. Thanks @jurialmunkey!

**Comment by jurialmunkey** [comment]
@roc16 - Can you try v4.11.19? Should fix it. Hopefully this is the last time I break the TVDB id library lookups!

**Comment by roc16** [comment]
Hi @jurialmunkey just tested and it's not fixed. I restarted after upgrading but no joy. Do you need a log from me?

**Comment by jurialmunkey** [comment]
Yeah, you're right. Something isn't working properly with caching the Kodi DB to memory.

**Comment by jurialmunkey** [comment]
Okay, *now* it should be fixed in v4.11.20... 

Such a dumb mistake. Left a setting as false from when I was testing something and forgot to flip it back to True before I committed. 

EDIT: Also it is worth pointing out that I'm now caching the Kodi Library to memory at startup for faster access in the player dialog. The downside is that the cache has a 3 hour expiry, so if you make changes to the library during that time to get those new details you either need to wait out the expiry, restart Kodi, or use the manual refresh button found under TMDbHelper Settings > Other.

I doubt in reality you would need to do a manual refresh of the cached items much (if ever at all). But please let me know if you do find it necessary and I can reduce the cache expiry or maybe add a setting to choose the duration.

**Comment by roc16** [comment]
Hi @jurialmunkey , that's it. Working better than ever now. The caching really makes a difference. 

Thanks for the explanation on caching. I'll keep an eye on it and get back to if I notice any changes. 

Thanks as usual.

**Comment by jurialmunkey** [comment]
Excellent! Thanks for reporting the bug and testing. Now lets just hope I don't break it again - I think three times is enough! 😉
